-- Create the prompts table
create table system_prompts (
  id bigint generated by default as identity primary key,
  prompt_text text not null,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) if needed, or leave public for hackathon speed
alter table system_prompts enable row level security;

create policy "Enable read access for all users" on system_prompts
  for select using (true);

create policy "Enable insert access for all users" on system_prompts
  for insert with check (true);
